### ISSUE TITLE
On Settings page, put labels next to input fields like First Name, Last Name, etc.

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www_myapnea_org#189]
This looks kind of weird when you go to Settings and just see your name, zip code, and birth year in boxes that you apparently can "Save Changes" for. Make the Settings page more like the Social Profile page in this regard.

**Comment by remomueller** [comment]
This was addressed in [Release 4.0](https://github.com/myapnea/www_myapnea_org/releases/tag/v4.0.0)
